FROM ubuntu:26.04 

EXPOSE 5173
RUN apt-get update && apt-get install -y --no-install-recommends nodejs npm curl unzip sudo vim-tiny
COPY stac-explorer-source.zip stac-explorer-source.zip
RUN unzip stac-explorer-source.zip
WORKDIR /STACExplorer
COPY vite.config.ts vite.config.ts
RUN npm install
ENTRYPOINT ["npm"]
CMD ["run", "dev"]